export const IPC_CHANNELS = {
  app: {
    checkForUpdates: 'app-check-for-updates',
  },
  system: {
    openPath: 'system-open-path',
  },
  project: {
    list: 'project-list',
    create: 'project-create',
    get: 'project-get',
    updatePrompt: 'project-update-prompt',
    updateAISettings: 'project-update-ai-settings',
    updateQASettings: 'project-update-qa-settings',
    listSavedPrompts: 'project-saved-prompt-list',
    createSavedPrompt: 'project-saved-prompt-create',
    updateSavedPrompt: 'project-saved-prompt-update',
    deleteSavedPrompt: 'project-saved-prompt-delete',
    remove: 'project-delete',
    getFiles: 'project-get-files',
    addFile: 'project-add-file',
    createPastedSourceFile: 'project-create-pasted-source-file',
  },
  file: {
    get: 'file-get',
    remove: 'file-delete',
    getSegments: 'file-get-segments',
    getPreview: 'file-get-preview',
    export: 'file-export',
    runQA: 'file-run-qa',
    inspect: 'file-inspect',
    exportReferences: 'file-export-references-for-mt',
    precheckSourceTerminology: 'file-precheck-source-terminology',
    cancelSourceTerminologyPrecheck: 'file-cancel-source-terminology-precheck',
  },
  segment: {
    update: 'segment-update',
  },
  tm: {
    getMatches: 'tm-get-matches',
    prefetch: 'tm-prefetch',
    concordance: 'tm-concordance',
    list: 'tm-list',
    preview: 'tm-preview',
    create: 'tm-create',
    remove: 'tm-delete',
    getMountedByProject: 'tm-project-mounted',
    mount: 'tm-mount',
    unmount: 'tm-unmount',
    commitFile: 'tm-commit-file',
    matchFile: 'tm-match-file',
    importPreview: 'tm-import-preview',
    importExecute: 'tm-import-execute',
    syncSetConfig: 'tm-sync-set-config',
    syncExecute: 'tm-sync-execute',
    syncCancel: 'tm-sync-cancel',
  },
  tb: {
    getMatches: 'tb-get-matches',
    prefetch: 'tb-prefetch',
    list: 'tb-list',
    preview: 'tb-preview',
    create: 'tb-create',
    remove: 'tb-delete',
    getMountedByProject: 'tb-project-mounted',
    mount: 'tb-mount',
    unmount: 'tb-unmount',
    importPreview: 'tb-import-preview',
    importExecute: 'tb-import-execute',
    syncSetConfig: 'tb-sync-set-config',
    syncExecute: 'tb-sync-execute',
  },
  ai: {
    getSettings: 'ai-settings-get',
    listConnections: 'ai:list-connections',
    testConnection: 'ai:test-connection',
    deleteConnection: 'ai:delete-connection',
    listProviders: 'ai-providers-list',
    addProvider: 'ai-provider-add',
    deleteProvider: 'ai-provider-delete',
    getProxySettings: 'proxy-settings-get',
    setProxySettings: 'proxy-settings-set',
    translateSegment: 'ai-translate-segment',
    refineSegment: 'ai-refine-segment',
    translateFile: 'ai-translate-file',
    cancelFileJob: 'ai-cancel-file-job',
    testTranslate: 'ai-test-translate',
  },
  dialog: {
    openFile: 'dialog-open-file',
    saveFile: 'dialog-save-file',
  },
  clipboard: {
    read: 'clipboard-read',
  },
  job: {
    getStatus: 'job-get-status',
  },
  events: {
    segmentsUpdated: 'segments-updated',
    segmentsUpdatedBatch: 'segments-updated-batch',
    appProgress: 'app-progress',
    jobProgress: 'job-progress',
    appUpdateStatus: 'app-update-status',
    referenceDataChanged: 'reference-data-changed',
  },
} as const;

export type IpcChannelMap = typeof IPC_CHANNELS;
