// This file is generated by scripts/generate-ai-prompt-templates.mjs.
// Do not edit manually; update the Markdown sources in packages/core/src/project/prompts/.

export const AI_PROMPT_TEMPLATE_CATALOG = {
  translation: {
    systemBaseRules:
      "From {{srcLang}} to {{tgtLang}}. Output in {{tgtLang}} ONLY.\nKeep all protected markers exactly as they appear, including forms such as {1>, <2}, {3}\nPreserve all escape sequences exactly as they appear, including \\n and \\r.\nReturn only the translated text, without quotes or extra commentary",
    sourceHeaderPlain: "Source ({{srcLang}}):",
    sourceHeaderProtected: "Source ({{srcLang}}, protected-marker format):",
    contextLine: "Context: {{context}}",
    currentTranslationLabel: "Current Translation:",
    refinementInstructionLabel: "Refinement Instruction:",
    tmHeader: "TM References (top matches):",
    tmEntrySummary: "- Similarity: {{similarity}}% | TM: {{tmName}}",
    tmEntrySource: "- Source: {{sourceText}}",
    tmEntryTarget: "- Target: {{targetText}}",
    concordanceHeader: "Concordance Suggestions:",
    concordanceEntrySummary: "- Match: {{matchedSourceText}} | TM: {{tmName}}",
    concordanceEntrySource: "- TM Source: {{sourceText}}",
    concordanceEntryTarget: "- TM Target: {{targetText}}",
    tbHeader: "Terminology References (hit terms):",
    tbEntry: "- {{srcTerm}} => {{tgtTerm}}{{noteSuffix}}",
    validationFeedbackHeader: "Validation feedback from previous attempt:",
  },
  custom: {
    defaultSystemBody:
      "You are a precise text processing assistant.\nFollow the user-provided instruction exactly.\nUse context when present.\nReturn only the final output text, without quotes or extra commentary.",
    inputHeaderPlain: "Input:",
    inputHeaderProtected: "Input (protected-marker format):",
    contextLine: "Context: {{context}}",
    validationFeedbackHeader: "Validation feedback from previous attempt:",
  },
} as const;

export type AIPromptTemplateCatalog = typeof AI_PROMPT_TEMPLATE_CATALOG;
