// This file is generated by scripts/generate-ai-prompt-templates.mjs.
// Do not edit manually; update the Markdown sources in packages/core/src/project/prompts/.

export const AI_PROMPT_TEMPLATE_CATALOG = {
  translation: {
    systemBaseRules:
      "From {{srcLang}} to {{tgtLang}}. Output in {{tgtLang}} ONLY.\nKeep all protected markers exactly as they appear, including forms such as {1>, <2}, {3}\nPreserve all escape sequences exactly as they appear, including \\n and \\r.\nReturn only the translated text, without quotes or extra commentary",
    sourceHeaderPlain: "Source ({{srcLang}}):",
    sourceHeaderProtected: "Source ({{srcLang}}, protected-marker format):",
    contextLine: "Context: {{context}}",
    currentTranslationLabel: "Current Translation:",
    refinementInstructionLabel: "Refinement Instruction:",
    tmHeader: "TM Reference (best match):",
    tmEntrySummary: "- Similarity: {{similarity}}% | TM: {{tmName}}",
    tmEntrySource: "- Source: {{sourceText}}",
    tmEntryTarget: "- Target: {{targetText}}",
    tbHeader: "Terminology References (hit terms):",
    tbEntry: "- {{srcTerm}} => {{tgtTerm}}{{noteSuffix}}",
    validationFeedbackHeader: "Validation feedback from previous attempt:",
  },
  review: {
    defaultSystemBody:
      "You are a professional reviewer.\nReview and improve the provided {{tgtLang}} text, using {{srcLang}} as source language.\nThe source can include protected markers such as {1>, <2}, {3}.\nNever translate, remove, reorder, renumber, or rewrite protected markers.\nKeep all tags, placeholders, and formatting exactly as they appear in the source.\nReturn only the reviewed text, without quotes or extra commentary.\nIf no edit is needed, returning the original text is allowed.",
    languageInstruction:
      "Original text language: {{srcLang}}. Translation text language: {{tgtLang}}.",
    sourceHeaderPlain: "Source ({{srcLang}}):",
    sourceHeaderProtected: "Source ({{srcLang}}, protected-marker format):",
    contextLine: "Context: {{context}}",
    validationFeedbackHeader: "Validation feedback from previous attempt:",
  },
  custom: {
    defaultSystemBody:
      "You are a precise text processing assistant.\nFollow the user-provided instruction exactly.\nUse context when present.\nReturn only the final output text, without quotes or extra commentary.",
    inputHeaderPlain: "Input:",
    inputHeaderProtected: "Input (protected-marker format):",
    contextLine: "Context: {{context}}",
    validationFeedbackHeader: "Validation feedback from previous attempt:",
  },
  dialogue: {
    introLine:
      "Translate the following dialogue segments from {{srcLang}} to {{tgtLang}}.",
    jsonContractIntro: "Return strict JSON only with this schema:",
    jsonContractSchema:
      '{"translations":[{"id":"<segment-id>","text":"<translated-text>"}]}',
    preserveIdLine: "Each output item must preserve its source id exactly.",
    noOmitIdsLine: "Never omit or add IDs.",
    segmentsHeader: "Dialogue Segments:",
    segmentIndexLine: "{{index}}. id: {{id}}",
    segmentSpeakerLine: "   speaker: {{speaker}}",
    segmentSourceLabel: "   source:",
    tmHeader: "   TM Reference (best match):",
    tmEntrySummary: "   - Similarity: {{similarity}}% | TM: {{tmName}}",
    tmEntrySource: "   - Source: {{sourceText}}",
    tmEntryTarget: "   - Target: {{targetText}}",
    tbHeader: "   Terminology References (hit terms):",
    tbEntry: "   - {{srcTerm}} => {{tgtTerm}}{{noteSuffix}}",
    previousGroupHeader: "Previous Dialogue Group (for consistency):",
    previousGroupSpeakerLine: "speaker: {{speaker}}",
    previousGroupSourceLabel: "source:",
    previousGroupTargetLabel: "target:",
    validationFeedbackHeader: "Validation feedback from previous attempt:",
  },
} as const;

export type AIPromptTemplateCatalog = typeof AI_PROMPT_TEMPLATE_CATALOG;
